#Browser Selection
browser = chrome
#Url Selection
Url = https://www.demoblaze.com
#Application UserName and Password
Username = Priya.test
password = test@123
#Input Data
title = Welcome Priya
#Billing Data
billingName = Priya
billingCountry = India
billingCity = Chennai
billingCredit = 12345678998765
billingMonth = March
billingYear = 2026